version: '3.1'

services:
  r-studio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8787:8787
    volumes:
      - ./src:/home/rstudio/data
    environment:
      - PASSWORD=yourpassword
    container_name: r-studio
    
